"""Initial CIVITAS persistence schema."""
from alembic import op
import sqlalchemy as sa
revision="0001"; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("users",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("google_sub",sa.String(255),nullable=False,unique=True),sa.Column("email",sa.String(320)),sa.Column("name",sa.String(255)),sa.Column("avatar_url",sa.String(2048)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("last_login_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_users_google_sub","users",["google_sub"])
    op.create_table("simulations",sa.Column("id",sa.String(36),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("seed",sa.Integer(),nullable=False),sa.Column("population",sa.Integer(),nullable=False),sa.Column("engine_version",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("current_day",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("finished_at",sa.DateTime(timezone=True)))
    op.create_index("ix_simulations_user_id","simulations",["user_id"]); op.create_index("ix_simulations_user_created","simulations",["user_id","created_at"])
    op.create_table("villages",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("simulation_id",sa.String(36),sa.ForeignKey("simulations.id",ondelete="CASCADE"),nullable=False),sa.Column("village_id",sa.Integer(),nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("food",sa.Float(),nullable=False),sa.Column("wood",sa.Float(),nullable=False),sa.Column("stone",sa.Float(),nullable=False),sa.UniqueConstraint("simulation_id","village_id",name="uq_village_simulation_id"))
    op.create_index("ix_villages_simulation_id","villages",["simulation_id"])
    op.create_table("agents",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("simulation_id",sa.String(36),sa.ForeignKey("simulations.id",ondelete="CASCADE"),nullable=False),sa.Column("agent_id",sa.Integer(),nullable=False),sa.Column("village_id",sa.Integer(),nullable=False),sa.Column("age",sa.Float(),nullable=False),sa.Column("health",sa.Float(),nullable=False),sa.Column("hunger",sa.Float(),nullable=False),sa.Column("wealth",sa.Float(),nullable=False),sa.Column("trust",sa.Float(),nullable=False),sa.Column("occupation",sa.String(32),nullable=False),sa.Column("alive",sa.Boolean(),nullable=False),sa.Column("fertility",sa.Float(),nullable=False),sa.Column("faction_id",sa.Integer()),sa.UniqueConstraint("simulation_id","agent_id",name="uq_agent_simulation_id"))
    op.create_index("ix_agents_simulation_id","agents",["simulation_id"])
    op.create_table("factions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("simulation_id",sa.String(36),sa.ForeignKey("simulations.id",ondelete="CASCADE"),nullable=False),sa.Column("faction_id",sa.Integer(),nullable=False),sa.Column("name",sa.String(255),nullable=False),sa.Column("leader_id",sa.Integer(),nullable=False),sa.Column("cohesion",sa.Float(),nullable=False),sa.Column("members",sa.Text(),nullable=False),sa.UniqueConstraint("simulation_id","faction_id",name="uq_faction_simulation_id"))
    op.create_index("ix_factions_simulation_id","factions",["simulation_id"])
    op.create_table("relationships",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("simulation_id",sa.String(36),sa.ForeignKey("simulations.id",ondelete="CASCADE"),nullable=False),sa.Column("agent_a",sa.Integer(),nullable=False),sa.Column("agent_b",sa.Integer(),nullable=False),sa.Column("trust",sa.Float(),nullable=False),sa.Column("interactions",sa.Integer(),nullable=False),sa.UniqueConstraint("simulation_id","agent_a","agent_b",name="uq_relationship_sim_agents"))
    op.create_index("ix_relationships_simulation_id","relationships",["simulation_id"])
    metric_cols=[("population",sa.Integer()),("living_population",sa.Integer()),("average_health",sa.Float()),("average_hunger",sa.Float()),("total_food",sa.Float()),("total_wood",sa.Float()),("total_stone",sa.Float()),("total_wealth",sa.Float()),("average_wealth",sa.Float()),("average_trust",sa.Float()),("trade_volume",sa.Float()),("births",sa.Integer()),("deaths",sa.Integer()),("migrations",sa.Integer()),("social_interactions",sa.Integer()),("conflicts",sa.Integer()),("faction_count",sa.Integer()),("average_faction_cohesion",sa.Float())]
    op.create_table("metrics",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("simulation_id",sa.String(36),sa.ForeignKey("simulations.id",ondelete="CASCADE"),nullable=False),sa.Column("day",sa.Integer(),nullable=False),*[sa.Column(n,t,nullable=False) for n,t in metric_cols],sa.UniqueConstraint("simulation_id","day",name="uq_metric_simulation_day"))
    op.create_index("ix_metrics_simulation_day","metrics",["simulation_id","day"])
    op.create_table("events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("simulation_id",sa.String(36),sa.ForeignKey("simulations.id",ondelete="CASCADE"),nullable=False),sa.Column("day",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(64),nullable=False),sa.Column("message",sa.Text(),nullable=False),sa.Column("agent_id",sa.Integer()),sa.Column("village_id",sa.Integer()),sa.Column("amount",sa.Float()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_events_simulation_day","events",["simulation_id","day"])
def downgrade():
    for table in ("events","metrics","relationships","factions","agents","villages","simulations","users"): op.drop_table(table)
